// URL base da API
@apiurl = http://127.0.0.1:5000
@auth-token = 

### Inserir novo cliente
POST {{apiurl}}/api/users/ HTTP/1.1
Content-Type: application/json

{ 
    "name" : "example",
    "email" : "example@mail.com",
    "password" : "pwd",
    "phone_number": "912345678"
}

### Autenticar cliente
PATCH {{apiurl}}/api/users/ HTTP/1.1
Content-Type: application/json

{ 
    "email": "example@mail.com",
    "password": "pwd"
}

### Terminar sessão do cliente
PATCH {{apiurl}}/api/users/logout/ HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

### Obter entidades ativas
GET {{apiurl}}/api/entities/ HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

### Obter detalhes de uma entidade
GET {{apiurl}}/api/entities/1/ HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

### Obter lista de entidades ativas e com ofertas para aquele dia
GET {{apiurl}}/api/entities/withoffers/ HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

### Obter lista de todas as ofertas ainda disponíveis para aquele dia
GET {{apiurl}}/api/entities/offers/ HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

### Obter lista de ofertas ainda disponíveis de uma entidade para aquele dia
GET {{apiurl}}/api/entities/offers/1/ HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

### Obter uma oferta
GET {{apiurl}}/api/offers/9/ HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

### Registar a compra de uma oferta
POST {{apiurl}}/api/entities/offers/buy/ HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

{ 
    "offer_id" : "6"
}

### Obter lista compras efetuadas pelo utilizador
GET {{apiurl}}/api/users/purchases/ HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

### Cancelar uma compra
PATCH {{apiurl}}/api/users/purchases/ HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

{
    "offer_id": "10"
}