-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 16:30:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FoodSaver
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FoodSaver
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FoodSaver` DEFAULT CHARACTER SET utf8 ;
USE `FoodSaver` ;

-- -----------------------------------------------------
-- Table `FoodSaver`.`entidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodSaver`.`entidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(256) NULL,
  `logotipo` VARCHAR(100) NULL,
  `morada` VARCHAR(200) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(150) NULL,
  `password` VARCHAR(200) NULL,
  `ativo` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodSaver`.`oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodSaver`.`oferta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `entidade_id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(256) NULL,
  `foto` VARCHAR(100) NULL,
  `preço` FLOAT NULL,
  `data` DATE NULL,
  `disponivel` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_oferta_entidade_idx` (`entidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_oferta_entidade`
    FOREIGN KEY (`entidade_id`)
    REFERENCES `FoodSaver`.`entidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodSaver`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodSaver`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `telefone` VARCHAR(45) NULL,
  `password` VARCHAR(200) NULL,
  `ativo` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodSaver`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodSaver`.`compra` (
  `oferta_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `pago` TINYINT(1) NULL,
  `levantado` TINYINT(1) NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`oferta_id`, `cliente_id`),
  INDEX `fk_compra_cliente1_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_compra_oferta1`
    FOREIGN KEY (`oferta_id`)
    REFERENCES `FoodSaver`.`oferta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `FoodSaver`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FoodSaver`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FoodSaver`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `nome` VARCHAR(100) NULL,
  `password` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

